name: Run tests

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16, 17, 18]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Pull sources
        uses: actions/checkout@v2
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Performance Meter
        run: npm install

      - name: Run tests
        run: node run.js